CREATE TABLE contribution (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contribution_name TEXT NOT NULL,
    ingredient_id INTEGER
        REFERENCES ingredient(id) ON DELETE CASCADE NOT NULL,
    recipe_id INTEGER
        REFERENCES recipe(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);